name: hacktrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.6
  cloudinary_url_gen: ^1.0.0
  cloudinary_flutter: ^1.3.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  video_player: ^2.7.0
  loading_animation_widget: ^1.3.0
  
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/bg.png
    - assets/logoo.png
