// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb_pmARxFb7qe6mnot_fmRJ_bcyvlYR94',
    appId: '1:191678683715:web:e7874d30bfd406c83952f6',
    messagingSenderId: '191678683715',
    projectId: 'hacktrack-42793',
    authDomain: 'hacktrack-42793.firebaseapp.com',
    storageBucket: 'hacktrack-42793.firebasestorage.app',
    measurementId: 'G-KEE2KH4NB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACFE8BOT9HciyJ9ot4tIy-CBbQY3aA6XU',
    appId: '1:191678683715:android:812cbe8ade4fda0e3952f6',
    messagingSenderId: '191678683715',
    projectId: 'hacktrack-42793',
    storageBucket: 'hacktrack-42793.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAocwh6qZUQAQjEoXRU-_BerIsK7p7s5UA',
    appId: '1:191678683715:ios:46446fc8b8a6e82b3952f6',
    messagingSenderId: '191678683715',
    projectId: 'hacktrack-42793',
    storageBucket: 'hacktrack-42793.firebasestorage.app',
    iosBundleId: 'com.example.hacktrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAocwh6qZUQAQjEoXRU-_BerIsK7p7s5UA',
    appId: '1:191678683715:ios:46446fc8b8a6e82b3952f6',
    messagingSenderId: '191678683715',
    projectId: 'hacktrack-42793',
    storageBucket: 'hacktrack-42793.firebasestorage.app',
    iosBundleId: 'com.example.hacktrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb_pmARxFb7qe6mnot_fmRJ_bcyvlYR94',
    appId: '1:191678683715:web:15d4495f480ee86c3952f6',
    messagingSenderId: '191678683715',
    projectId: 'hacktrack-42793',
    authDomain: 'hacktrack-42793.firebaseapp.com',
    storageBucket: 'hacktrack-42793.firebasestorage.app',
    measurementId: 'G-53P2FVZY1D',
  );
}
